var searchData=
[
  ['peakfinding_2ecpp',['peakfinding.cpp',['../peakfinding_8cpp.html',1,'']]],
  ['peakfinding_2eh',['peakfinding.h',['../peakfinding_8h.html',1,'']]],
  ['plotmakerdialog_2ecpp',['plotmakerdialog.cpp',['../plotmakerdialog_8cpp.html',1,'']]],
  ['plotmakerdialog_2eh',['plotmakerdialog.h',['../plotmakerdialog_8h.html',1,'']]],
  ['plotviewer_2ecpp',['plotviewer.cpp',['../plotviewer_8cpp.html',1,'']]],
  ['plotviewer_2eh',['plotviewer.h',['../plotviewer_8h.html',1,'']]],
  ['plotwidget_2ecpp',['plotwidget.cpp',['../plotwidget_8cpp.html',1,'']]],
  ['plotwidget_2eh',['plotwidget.h',['../plotwidget_8h.html',1,'']]],
  ['pls_2ecpp',['pls.cpp',['../pls_8cpp.html',1,'']]],
  ['plsdata_2ecpp',['plsdata.cpp',['../plsdata_8cpp.html',1,'']]],
  ['plsdata_2eh',['plsdata.h',['../plsdata_8h.html',1,'']]],
  ['plsdialog_2ecpp',['plsdialog.cpp',['../plsdialog_8cpp.html',1,'']]],
  ['plsdialog_2eh',['plsdialog.h',['../plsdialog_8h.html',1,'']]],
  ['principalcomponentsdata_2ecpp',['principalcomponentsdata.cpp',['../principalcomponentsdata_8cpp.html',1,'']]],
  ['principalcomponentsdata_2eh',['principalcomponentsdata.h',['../principalcomponentsdata_8h.html',1,'']]],
  ['principalcomponentsdialog_2ecpp',['principalcomponentsdialog.cpp',['../principalcomponentsdialog_8cpp.html',1,'']]],
  ['principalcomponentsdialog_2eh',['principalcomponentsdialog.h',['../principalcomponentsdialog_8h.html',1,'']]],
  ['pythonshelldialog_2ecpp',['pythonshelldialog.cpp',['../pythonshelldialog_8cpp.html',1,'']]],
  ['pythonshelldialog_2eh',['pythonshelldialog.h',['../pythonshelldialog_8h.html',1,'']]]
];
